server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: ${AUTH0_ISSUER_URI}

client:
  base-url: ${CLIENT_BASE_URL}
